name: Windows CI

on: [push, pull_request]

permissions:
  contents: read

# Cancels previous runs of the same workflow
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  Windows:
    name: Windows (Native OPAM)
    runs-on: windows-latest
    timeout-minutes: 45
    steps:
      - name: ğŸ”­ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ« Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14
          dune-cache: true
          opam-local-packages: |
            coqide-server.opam
            rocq-*.opam

      - name: ğŸ«ğŸªğŸ« Get Rocq dependencies
        run: opam install --deps-only ./coqide-server.opam ./rocq-*.opam

      - name: ğŸ§± Build Rocq
        run: opam exec -- make world

      - name: ğŸ« Get test suite deps
        run: opam install ounit2 conf-python-3 conf-time

      - name: ğŸ› Test Rocq
        run: opam exec -- make -j 4 -C test-suite DISABLED_SUBSYSTEMS='misc coq-makefile precomputed-time-tests'
